name: maven-pipeline

on: [push, pull_request]

jobs:

  codecov-checkstyle-maven-linux-single-pom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "deploy codecov checkstyle maven(single pom) on bionic arm64"        
      run: |
            cd maven-checkstyle && mvn checkstyle:checkstyle
            bash <(curl -s https://codecov.io/bash)        


  # gradle-make-findbugs-blackduckcopilot:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: os fingerprinting
  #     run: hostnamectl status    
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: Build with Gradle
  #     run: sudo make deploy-app4

  # gradle-make-jacoco-coveralls:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: os fingerprinting
  #     run: hostnamectl status    
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: Build with Gradle
  #     run: sudo make deploy-app5
      
  # gradle-jacoco-coveralls:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: os fingerprinting
  #     run: hostnamectl status    
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: Change dir
  #     run: cd app5 && chmod +x gradlew
  #   - name: Build with Gradle
  #     run: "./gradlew clean build"    
  #   - name: Create jacoco coveralls report
  #     run: "./gradlew jacocoTestReport coveralls"             

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: Run a one-line script
  #     run: echo Hello, world!

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: Run a one-line script
  #     run: echo Hello, world!